name: CI/CD Pipeline for GitHub Gist API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install development dependencies
        run: |
          pip install flake8 pytest pytest-cov safety


      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

     
      - name: Run tests with coverage
        run: |
          pytest --cov=.

  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64


  deploy:
    runs-on: ubuntu-latest
    needs: build-test-analyze # Ensures deployment only happens if tests pass
    environment: production # Optional: define an environment for deployment tracking

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v3 # Action to install kubectl on the runner

      - name: Configure Kubeconfig
        run: |
          # This assumes your KUBE_CONFIG secret contains the base64 encoded kubeconfig
          # If it's plain text, just write it directly.
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "Kubeconfig configured successfully."
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          # Create the k8s directory if it doesn't exist locally on the runner for applying
          mkdir -p k8s
          # Create the deployment.yaml and service.yaml directly from the workflow
          # This ensures the image tag is dynamically updated based on the build
          cat <<EOF > k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-gist-api-deployment
  labels:
    app: github-gist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-gist-api
  template:
    metadata:
      labels:
        app: github-gist-api
    spec:
      containers:
      - name: github-gist-api
        image: ghcr.io/${{ github.repository }}:latest # This is correctly interpolated here
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
EOF
          cat <<EOF > k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: github-gist-api-service
  labels:
    app: github-gist-api
spec:
  selector:
    app: github-gist-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
EOF
          # Apply the manifests
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          echo "Deployment to Kubernetes complete."
